### ISSUE TITLE
安卓9以上运行错误

### ISSUE THREAD

**Issue by LoveHikari** [wuxiaosu/XposedRimetHelper#13]
Unable to start activity ComponentInfo{com.wuxiaosu.rimethelper/com.wuxiaosu.rimethelper.activity.MainActivity}: android.view.InflateException: Binary XML file line #21: Binary XML file line #21: Error inflating class com.wuxiaosu.widget.SettingLabelView

**Comment by wuxiaosu** [comment]
在 project build.gradle 中添加

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://raw.githubusercontent.com/wuxiaosu/MvnRepository/master'
        }
    }
}
