### ISSUE TITLE
您好,我这边有个特殊需求,对=修改包名以后,对某个软件不生效,有偿

### ISSUE THREAD

**Issue by HiColinn** [wuxiaosu/XposedRimetHelper#16]
您好,我这边有个特殊需求,修改包名以后,对某个软件不生效,可以有偿帮解决一下吗

**Comment by wuxiaosu** [comment]
什么软件

**Comment by HiColinn** [comment]
> 什么软件

王者荣耀,目测需要Hook GnssStatus,不会

**Comment by wuxiaosu** [comment]
> > 什么软件
> 
> 王者荣耀,目测需要Hook GnssStatus,不会

不是这个问题，还有其他内容需要处理

**Comment by HiColinn** [comment]
> > > 什么软件
> > 
> > 
> > 王者荣耀,目测需要Hook GnssStatus,不会
> 
> 不是这个问题，还有其他内容需要处理

时间方便吗?可以帮解决一下吗?可以有偿.怎么练习您呢

**Comment by HiColinn** [comment]
目前国内xposed开发这一块的学习资料比较少,我本身也是刚接触这个,对hook用的不熟,我找了很多资料,尝试了好多方法都解决不了,目前普遍存在的问题就是对微信QQ钉钉什么的,都能成功定位,就是对王者荣耀不行,
猜测的原因是王者荣耀不仅需要经纬度坐标,还需要获取GPS卫星状态,但是android7以上,GpsStatus这个类已经废弃了,网上也找不到类似的demo,
您的时间也很宝贵,所以希望您能给个解决办法,逻辑什么的不重要,只要能成功定位就行,我会支付一些酬劳来感谢您的帮助.

**Comment by wuxiaosu** [comment]
> 目前国内xposed开发这一块的学习资料比较少,我本身也是刚接触这个,对hook用的不熟,我找了很多资料,尝试了好多方法都解决不了,目前普遍存在的问题就是对微信QQ钉钉什么的,都能成功定位,就是对王者荣耀不行,
> 猜测的原因是王者荣耀不仅需要经纬度坐标,还需要获取GPS卫星状态,但是android7以上,GpsStatus这个类已经废弃了,网上也找不到类似的demo,
> 您的时间也很宝贵,所以希望您能给个解决办法,逻辑什么的不重要,只要能成功定位就行,我会支付一些酬劳来感谢您的帮助.

我QQ 1044205037
