### ISSUE TITLE
有没有研究过钉钉过模拟器的检测呀

### ISSUE THREAD

**Issue by w1nds** [wuxiaosu/XposedRimetHelper#4]
rt

**Comment by wuxiaosu** [comment]
并没有，没需求，也基本不用钉钉了

**Comment by zhonghuaifang** [comment]
看这个项目https://github.com/Hilaver/MockGPS
实测钉钉打卡检测的是软件包名，所以自己打包个软件，换个包名就可以打卡不被检测到了，更换包名需要重新申请地图的sdk，不然地图不会加载。应该是这样...
