### ISSUE TITLE
软件很不错的

### ISSUE THREAD

**Issue by qq31582839** [wuxiaosu/XposedRimetHelper#8]
你好，请问你有联系方式吗，想给你支持一点，发个红包给你

**Comment by wuxiaosu** [comment]
在520评论说要给我发红包的，怕不是要发几百块？
![qrcode.png](https://raw.githubusercontent.com/wuxiaosu/XposedWechatHelper/master/wechathelper/src/main/res/drawable-xhdpi/qrcode.png)
